### PR TITLE
Some bug fixes for ASStackLayoutSpec

### LINKED ISSUE #3151: [ASStackLayoutSpec] Crash during layout since commit 415005
Hi guys,

I have a crash during layout since commit 415005 (without changing anything to my code). It is related to the stack layout spec. Everything works fine before this commit. ASDK crashes in `flexLinesAlongStackDimension`, during assertion

```
ASDisplayNodeCAssert(firstFlexItem != -1, @"At this point there must be at least 1 flexible item");
```

Here's the stack trace:

```
* thread #24: tid = 0x37a3ba, 0x000000018ef87014 libsystem_kernel.dylib`__pthread_kill + 8, queue = 'com.apple.root.default-qos', stop reason = signal SIGABRT
    frame #0: 0x000000018ef87014 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x000000018f04f450 libsystem_pthread.dylib`pthread_kill + 112
    frame #2: 0x000000018eefb400 libsystem_c.dylib`abort + 140
    frame #3: 0x000000018e9c52d4 libc++abi.dylib`abort_message + 132
    frame #4: 0x000000018e9e2cc0 libc++abi.dylib`default_terminate_handler() + 304
    frame #5: 0x000000018e9f0844 libobjc.A.dylib`_objc_terminate() + 124
    frame #6: 0x000000018e9df66c libc++abi.dylib`std::__terminate(void (*)()) + 16
    frame #7: 0x000000018e9def84 libc++abi.dylib`__cxa_throw + 136
    frame #8: 0x000000018e9f0690 libobjc.A.dylib`objc_exception_throw + 364
    frame #9: 0x000000018ffb908c CoreFoundation`+[NSException raise:format:arguments:] + 104
    frame #10: 0x0000000190a71098 Foundation`-[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 88
  * frame #11: 0x0000000100fe4688 AsyncDisplayKit`flexLinesAlongStackDimension(lines=size=1, style=0x000000016e9c8998, sizeRange=0x000000016e9c8a28, parentSize=(width = 52.5, height = 18), useOptimizedFlexing=NO) + 1840 at ASStackUnpositionedLayout.mm:592
    frame #12: 0x0000000100fe2ae8 AsyncDisplayKit`ASStackUnpositionedLayout::compute(children=size=4, style=0x000000016e9c8998, sizeRange=0x000000016e9c8a28) + 512 at ASStackUnpositionedLayout.mm:716
    frame #13: 0x0000000100fdd7f0 AsyncDisplayKit`::-[ASStackLayoutSpec calculateLayoutThatFits:](self=0x00000001741a38e0, _cmd="calculateLayoutThatFits:", constrainedSize=(min = (width = 52.5, height = 18), max = (width = 52.5, height = 18))) + 352 at ASStackLayoutSpec.mm:139
    frame #14: 0x0000000100f9307c AsyncDisplayKit`::-[ASLayoutSpec calculateLayoutThatFits:restrictedToSize:relativeToParentSize:](self=0x00000001741a38e0, _cmd="calculateLayoutThatFits:restrictedToSize:relativeToParentSize:", constrainedSize=(min = (width = 52.5, height = 18), max = (width = 52.5, height = 18)), parentSize=(width = NaN, height = NaN)) + 412 at ASLayoutSpec.mm:108
    frame #15: 0x0000000100f92e8c AsyncDisplayKit`::-[ASLayoutSpec layoutThatFits:parentSize:](self=0x00000001741a38e0, _cmd="layoutThatFits:parentSize:", constrainedSize=(min = (width = 52.5, height = 18), max = (width = 52.5, height = 18)), parentSize=(width = NaN, height = NaN)) + 256 at ASLayoutSpec.mm:100
    frame #16: 0x0000000100fe60f8 AsyncDisplayKit`crossChildLayout(child=0x00000001703cdf98, style=0x000000016e9c98a8, stackMin=18, stackMax=18, crossMin=52.5, crossMax=52.5, parentSize=(width = NaN, height = NaN)) + 384 at ASStackUnpositionedLayout.mm:67
    frame #17: 0x0000000100fee6dc AsyncDisplayKit`::___ZL31stretchItemsAlongCrossDimensionRNSt3__16vectorI21ASStackLayoutSpecItemNS_9allocatorIS1_EEEERK22ASStackLayoutSpecStyle6CGSized_block_invoke((null)=<unavailable>, i=1) + 388 at ASStackUnpositionedLayout.mm:212
    frame #18: 0x0000000100fe5cb8 AsyncDisplayKit`dispatchApplyIfNeeded(iterationCount=2, work=0x0000000100fee558) block_pointer) + 192 at ASStackUnpositionedLayout.mm:85
    frame #19: 0x0000000100fee54c AsyncDisplayKit`stretchItemsAlongCrossDimension(items=size=2, style=0x000000016e9c98a8, parentSize=(width = NaN, height = NaN), crossSize=52.5) + 164 at ASStackUnpositionedLayout.mm:202
    frame #20: 0x0000000100fe569c AsyncDisplayKit`stretchLinesAlongCrossDimension(lines=size=1, style=0x000000016e9c98a8, sizeRange=0x000000016e9c9938, parentSize=(width = NaN, height = NaN)) + 1060 at ASStackUnpositionedLayout.mm:242
    frame #21: 0x0000000100fe2b20 AsyncDisplayKit`ASStackUnpositionedLayout::compute(children=size=2, style=0x000000016e9c98a8, sizeRange=0x000000016e9c9938) + 568 at ASStackUnpositionedLayout.mm:723
    frame #22: 0x0000000100fdd7f0 AsyncDisplayKit`::-[ASStackLayoutSpec calculateLayoutThatFits:](self=0x00000001741a63c0, _cmd="calculateLayoutThatFits:", constrainedSize=(min = (width = 0, height = 0), max = (width = +Inf, height = +Inf))) + 352 at ASStackLayoutSpec.mm:139
    frame #23: 0x0000000100f9307c AsyncDisplayKit`::-[ASLayoutSpec calculateLayoutThatFits:restrictedToSize:relativeToParentSize:](self=0x00000001741a63c0, _cmd="calculateLayoutThatFits:restrictedToSize:relativeToParentSize:", constrainedSize=(min = (width = 0, height = 0), max = (width = +Inf, height = +Inf)), parentSize=(width = NaN, height = NaN)) + 412 at ASLayoutSpec.mm:108
    frame #24: 0x0000000100f92e8c AsyncDisplayKit`::-[ASLayoutSpec layoutThatFits:parentSize:](self=0x00000001741a63c0, _cmd="layoutThatFits:parentSize:", constrainedSize=(min = (width = 0, height = 0), max = (width = +Inf, height = +Inf)), parentSize=(width = NaN, height = NaN)) + 256 at ASLayoutSpec.mm:100
    frame #25: 0x0000000100fe60f8 AsyncDisplayKit`crossChildLayout(child=0x00000001703c5a78, style=0x000000016e9ca608, stackMin=0, stackMax=+Inf, crossMin=0, crossMax=+Inf, parentSize=(width = NaN, height = NaN)) + 384 at ASStackUnpositionedLayout.mm:67
    frame #26: 0x0000000100fe5f50 AsyncDisplayKit`::___ZL43layoutItemsAlongUnconstrainedStackDimensionRNSt3__16vectorI21ASStackLayoutSpecItemNS_9allocatorIS1_EEEERK22ASStackLayoutSpecStyleRK11ASSizeRange6CGSizeb_block_invoke((null)=<unavailable>, i=1) + 440 at ASStackUnpositionedLayout.mm:670
    frame #27: 0x0000000100fe5cb8 AsyncDisplayKit`dispatchApplyIfNeeded(iterationCount=2, work=0x0000000100fe5d98) block_pointer) + 192 at ASStackUnpositionedLayout.mm:85
    frame #28: 0x0000000100fe3484 AsyncDisplayKit`layoutItemsAlongUnconstrainedStackDimension(items=size=2, style=0x000000016e9ca608, sizeRange=0x000000016e9ca698, parentSize=(width = NaN, height = NaN), useOptimizedFlexing=NO) + 272 at ASStackUnpositionedLayout.mm:665
    frame #29: 0x0000000100fe2aa4 AsyncDisplayKit`ASStackUnpositionedLayout::compute(children=size=2, style=0x000000016e9ca608, sizeRange=0x000000016e9ca698) + 444 at ASStackUnpositionedLayout.mm:706
    frame #30: 0x0000000100fdd7f0 AsyncDisplayKit`::-[ASStackLayoutSpec calculateLayoutThatFits:](self=0x00000001741a7460, _cmd="calculateLayoutThatFits:", constrainedSize=(min = (width = 0, height = 0), max = (width = 351, height = +Inf))) + 352 at ASStackLayoutSpec.mm:139
    frame #31: 0x0000000100f9307c AsyncDisplayKit`::-[ASLayoutSpec calculateLayoutThatFits:restrictedToSize:relativeToParentSize:](self=0x00000001741a7460, _cmd="calculateLayoutThatFits:restrictedToSize:relativeToParentSize:", constrainedSize=(min = (width = 0, height = 0), max = (width = 351, height = +Inf)), parentSize=(width = NaN, height = NaN)) + 412 at ASLayoutSpec.mm:108
    frame #32: 0x0000000100f92e8c AsyncDisplayKit`::-[ASLayoutSpec layoutThatFits:parentSize:](self=0x00000001741a7460, _cmd="layoutThatFits:parentSize:", constrainedSize=(min = (width = 0, height = 0), max = (width = 351, height = +Inf)), parentSize=(width = NaN, height = NaN)) + 256 at ASLayoutSpec.mm:100
    frame #33: 0x0000000100fe60f8 AsyncDisplayKit`crossChildLayout(child=0x0000000106dae1e0, style=0x000000016fd9f818, stackMin=0, stackMax=+Inf, crossMin=0, crossMax=351, parentSize=(width = NaN, height = NaN)) + 384 at ASStackUnpositionedLayout.mm:67
    frame #34: 0x0000000100fe5f50 AsyncDisplayKit`::___ZL43layoutItemsAlongUnconstrainedStackDimensionRNSt3__16vectorI21ASStackLayoutSpecItemNS_9allocatorIS1_EEEERK22ASStackLayoutSpecStyleRK11ASSizeRange6CGSizeb_block_invoke((null)=<unavailable>, i=0) + 440 at ASStackUnpositionedLayout.mm:670
    frame #35: 0x0000000100fe6784 AsyncDisplayKit`::___ZL15ASDispatchApplymPU28objcproto17OS_dispatch_queue8NSObjectmU13block_pointerFvmE_block_invoke((null)=<unavailable>) + 116 at ASDispatch.h:27
    frame #36: 0x0000000102179258 libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #37: 0x0000000102179218 libdispatch.dylib`_dispatch_client_callout + 16
    frame #38: 0x0000000102187330 libdispatch.dylib`_dispatch_queue_override_invoke + 1176
    frame #39: 0x0000000102188e2c libdispatch.dylib`_dispatch_root_queue_drain + 584
    frame #40: 0x0000000102188b78 libdispatch.dylib`_dispatch_worker_thread3 + 140
    frame #41: 0x000000018f04b2a0 libsystem_pthread.dylib`_pthread_wqthread + 1288
    frame #42: 0x000000018f04ad8c libsystem_pthread.dylib`start_wqthread + 4
```

And here's the content of the `children` vector in `ASStackUnpositionedLayout`:

```
{
  [0] = {
    element = 0x000000017417d280
    style = 0x000000010a63a950
    size = {
      width = (unit = ASDimensionUnitAuto, value = 0)
      height = (unit = ASDimensionUnitAuto, value = 0)
      minWidth = (unit = ASDimensionUnitAuto, value = 0)
      maxWidth = (unit = ASDimensionUnitAuto, value = 0)
      minHeight = (unit = ASDimensionUnitAuto, value = 0)
      maxHeight = (unit = ASDimensionUnitAuto, value = 0)
    }
  }
  [1] = {
    element = 0x0000000103144200
    style = 0x0000000106d99990
    size = {
      width = (unit = ASDimensionUnitAuto, value = 0)
      height = (unit = ASDimensionUnitAuto, value = 0)
      minWidth = (unit = ASDimensionUnitAuto, value = 0)
      maxWidth = (unit = ASDimensionUnitAuto, value = 0)
      minHeight = (unit = ASDimensionUnitAuto, value = 0)
      maxHeight = (unit = ASDimensionUnitAuto, value = 0)
    }
  }
  [2] = {
    element = 0x00000001741386a0
    style = 0x0000000106daa930
    size = {
      width = (unit = ASDimensionUnitAuto, value = 0)
      height = (unit = ASDimensionUnitAuto, value = 0)
      minWidth = (unit = ASDimensionUnitAuto, value = 0)
      maxWidth = (unit = ASDimensionUnitAuto, value = 0)
      minHeight = (unit = ASDimensionUnitAuto, value = 0)
      maxHeight = (unit = ASDimensionUnitAuto, value = 0)
    }
  }
  [3] = {
    element = 0x00000001028d5c00
    style = 0x00000001025b2ac0
    size = {
      width = (unit = ASDimensionUnitPoints, value = 30)
      height = (unit = ASDimensionUnitPoints, value = 18)
      minWidth = (unit = ASDimensionUnitAuto, value = 0)
      maxWidth = (unit = ASDimensionUnitAuto, value = 0)
      minHeight = (unit = ASDimensionUnitAuto, value = 0)
      maxHeight = (unit = ASDimensionUnitAuto, value = 0)
    }
  }
}
```

Putting up a full example project might be a bit tricky, I hope this is enough.
Any ideas, @nguyenhuy ?

Cheers,
Flo

### PR DESCRIPTION
**Pull request by nguyenhuy**
- Avoid returning a `NaN` `flexShrinkAdjustment`.
- Bail early (instead of assert) if a line has a positive `flexFactorSum` but then no flexible item can be found via flex adjustments, for example because the flexible items have zero size. Fixes #3151.
- Continue flexing other lines when one line is inflexible.
- Add unit test for the first 2 fixes.

### CODE REVIEW

File: Tests/ASStackLayoutSpecSnapshotTests.mm [hunk 1]
```diff
@@ -1044,11 +1044,31 @@ - (void)testNegativeViolationIsDistributedBasedOnSizeAndFlexFactorDoesNotShrinkT
...
+- (void)testNegativeViolationAndFlexFactorIsNotRespected
+{
+  ASStackLayoutSpecStyle style = {.direction = ASStackLayoutDirectionHorizontal};
+  
+  NSArray<ASDisplayNode *> *subnodes = @[
+    ASDisplayNodeWithBackgroundColor([UIColor redColor], {50, 50}),
+    ASDisplayNodeWithBackgroundColor([UIColor yellowColor], CGSizeZero),
+  ];
+  
+  subnodes[1].style.flexShrink = 0;
```
Comment (maicki) [inline Tests/ASStackLayoutSpecSnapshotTests.mm]: Should this be `subnodes[0]`?

Comment (nguyenhuy) [inline Tests/ASStackLayoutSpecSnapshotTests.mm]: LOL it is!
