### PR TITLE
Fix collection view data inconsistency

### LINKED ISSUE #654: Assertion failure in -[ASCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3505.4/UICollectionView.m:3994
I am often getting this exception thrown with my ASCollectionView when reloadData is called. I have seen this pop up pretty regularly, but not all the time. Seems to happen more often when I have a breakpoint set in Xcode.

```
- (void)rangeController:(ASRangeController *)rangeController didDeleteSectionsAtIndexSet:(NSIndexSet *)indexSet withAnimationOptions:(ASDataControllerAnimationOptions)animationOptions
{
  ASDisplayNodeAssertMainThread();

  if (!self.asyncDataSource) {
    return; // if the asyncDataSource has become invalid while we are processing, ignore this request to avoid crashes
  }

  if (_performingBatchUpdates) {
    [_batchUpdateBlocks addObject:^{
      [super deleteSections:indexSet];
    }];
  } else {
    [UIView performWithoutAnimation:^{
      [super deleteSections:indexSet]; // !!!!! <NSMutableIndexSet: 0x1355b4310>[number of indexes: 1 (in 1 ranges), indexes: (0)]
    }];
  }
}
```

### PR DESCRIPTION
**Pull request by adly-holler**
This resolves #654

We could remove the flag and just call `[self layoutIfNeeded]` immediately after `[super reloadData]`
  - + Reduces complexity of ASCollectionView
  - - Relies on implementation details of `UICollectionView`
  - - Performance cost

### CODE REVIEW

File: AsyncDisplayKit/ASCollectionView.mm [hunk 1]
```diff
@@ -638,7 +648,7 @@ - (void)rangeControllerBeginUpdates:(ASRangeController *)rangeController {
 - (void)rangeController:(ASRangeController *)rangeController endUpdatesAnimated:(BOOL)animated completion:(void (^)(BOOL))completion {
   ASDisplayNodeAssertMainThread();
 
-  if (!self.asyncDataSource) {
+  if (!self.asyncDataSource || _pendingReloadData) {
     if (completion) {
       completion(NO);
```
Comment (adly-holler) [inline AsyncDisplayKit/ASCollectionView.mm]: Should we call `completion(YES)` if we suppressed the update due to a pending reload?

**Comment by eanagel** [comment]
@adly-holler, this is some great detective work! The idea of simply calling layoutIfNeeded after our reloadData is very attractive indeed. (Would that actually drop this down to a 1-line commit?) You mention performance cost as a drawback to this approach, could you expand on that a bit?

**Comment by eanagel** [comment]
Oh yes and another question, is this a potential problem for ASTableView as well? Have you explored that side of the equation?

**Comment by adly-holler** [comment]
@eanagel Thanks! It would indeed make this a 1-line commit, assuming that `reloadData` -> `setNeedsLayout` which I'd bet it does. The performance cost comes from laying out the cells when they don't necessarily need to be laid out. For a simple example, consider if you called `reloadData` 5 times during the same frame. The collection view cells would get laid out 5 times for one frame.

**Comment by appleguy** [comment]
Will analyze more, merging as it does fix the test project submitted recently.

**Comment by adly-holler** [comment]
Note: Ported the sample project to table view and I'm not seeing the same issue.
