### PR TITLE
[ASDisplayNode] Remove thread affinity for _displaysAsynchronously

### LINKED ISSUE #2517: [ASDisplayNode] _displaysAsynchronously is not safe to call off the main thread
We're seeing an assertion in `_displaysAsynchronously` for calling it off the main thread. I believe the assertion is incorrect and we should instead be holding the `__instanceLock__`. Currently, `_pendingLayoutTransitionDidComplete` calls it and that method should be able to run off the main thread I believe.

### PR DESCRIPTION
**Pull request by maicki**
Resolves #2517

### CODE REVIEW

File: AsyncDisplayKit/ASDisplayNode.mm [hunk 1]
```diff
@@ -1242,7 +1242,6 @@ - (BOOL)displaysAsynchronously
  */
 - (BOOL)_displaysAsynchronously
 {
-  ASDisplayNodeAssertThreadAffinity(self);
   return _flags.synchronous == NO && _flags.displaysAsynchronously;
```
Comment (garrettmoon) [inline AsyncDisplayKit/ASDisplayNode.mm]: Needs a lock too, no?

Comment (garrettmoon) [inline AsyncDisplayKit/ASDisplayNode.mm]: Nm, this one specifically avoids locking.
