### PR TITLE
[ASVideoPlayerNode] Fixes and improvements

### LINKED ISSUE #3042: [ASVideoPlayerNode] Crash initialising videoplayer node
Im getting a crash initialising ASVideoPlayerNode inside my ASCellNode.
looking at the diff i think [this](https://github.com/facebook/AsyncDisplayKit/commit/f7a0ac9760be7dc8c532fa7f9f232c5dcf738a30#diff-d560a1b1d55d40fbeef7c555fbeb22e9) caused the problem.

cc @nguyenhuy 

[Sample code](https://github.com/facebook/AsyncDisplayKit/files/783197/ASVideoPlayerNode.Crash.zip)

```
2017-02-17 09:56:45.642 Starflow[20538:8744927] *** Assertion failure in -[ASVideoNode setAsset:], /Users/marvinnazari/Code/Starflow/iOS/Pods/AsyncDisplayKit/AsyncDisplayKit/ASVideoNode.mm:499
2017-02-17 09:56:45.718 Starflow[20538:8744927] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'This method must be called on the main thread'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001088cbd4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001064c221e objc_exception_throw + 48
	2   CoreFoundation                      0x00000001088cfe42 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010605766d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   AsyncDisplayKit                     0x000000010377f66a -[ASVideoNode setAsset:] + 298
	5   AsyncDisplayKit                     0x0000000103782b8e -[ASVideoPlayerNode _init] + 318
	6   AsyncDisplayKit                     0x0000000103781fa7 -[ASVideoPlayerNode init] + 183
	7   Starflow                            0x00000001021b43b0 _TTOFCSo17ASVideoPlayerNodecfT_S_ + 16
	8   Starflow                            0x00000001021b2a84 _TFCSo17ASVideoPlayerNodeCfT_S_ + 68
	9   Starflow                            0x0000000102271554 _TFC8Starflow5NNOdecfT8isActiveSb_S0_ + 52
	10  Starflow                            0x00000001022713c4 _TFC8Starflow5NNOdeCfT8isActiveSb_S0_ + 52
	11  Starflow                            0x0000000102271386 _TFFC8Starflow31SFVideoCollectionViewController14collectionNodeFTCSo16ASCollectionNode18nodeBlockForItemAtV10Foundation9IndexPath_FT_CSo10ASCellNodeU_FT_S4_ + 22
	12  Starflow                            0x00000001020d2d17 _TTRXFo__oCSo10ASCellNode_XFdCb__aS__ + 39
	13  AsyncDisplayKit                     0x0000000103616fe8 __56-[ASCollectionView dataController:nodeBlockAtIndexPath:]_block_invoke_3.619 + 104
	14  AsyncDisplayKit                     0x00000001036ac2af -[ASIndexedNodeContext node] + 127
	15  AsyncDisplayKit                     0x0000000103629de2 __45-[ASDataController _layoutNodesFromContexts:]_block_invoke + 162
	16  AsyncDisplayKit                     0x0000000103639810 ___ZL15ASDispatchApplymPU28objcproto17OS_dispatch_queue8NSObjectmU13block_pointerFvmE_block_invoke + 80
	17  libdispatch.dylib                   0x000000010a62d978 _dispatch_call_block_and_release + 12
	18  libdispatch.dylib                   0x000000010a6570cd _dispatch_client_callout + 8
	19  libdispatch.dylib                   0x000000010a636445 _dispatch_queue_override_invoke + 1733
	20  libdispatch.dylib                   0x000000010a638385 _dispatch_root_queue_drain + 720
	21  libdispatch.dylib                   0x000000010a638059 _dispatch_worker_thread3 + 123
	22  libsystem_pthread.dylib             0x000000010aa06712 _pthread_wqthread + 1299
	23  libsystem_pthread.dylib             0x000000010aa061ed start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

### PR DESCRIPTION
**Pull request by maicki**
This PR is building on top of the fabulous work of @nguyenhuy in #3093.

Some problems in ASVideoPlayerNode currently:
* We have two sources of truth. One is the asset within the `ASVideoPlayerNode` and the other one is within the backing `ASVideoNode`. Ideally we only want to have only one final source of truth, therefore this PR will try to use the `ASVideoNode` as final truth of source.
* `_loadAssetWhenNodeBecomesVisible` isn't turned on in the empty initializer. This causes an assertion in #3042 because it's not safe to set an asset on ASVideoNode off main.
* The flag itself is troublesome. It's enabled by default, but even so, "visible" is a bit too late. The asset can be loaded as soon as the player enters preload state, which is what ASVideoNode is doing.
This PR deprecates _loadAssetWhenNodeBecomesVisible and fixes #3042 by letting ASVideoPlayerNode handles its objects automatically.
* The API does not align with UIKit components. Therefore a couple of initializer related to initialization with an URL are deprecated and replaced.

@MarvinNazari Would be great if you can comment and help me to test this PR. Thank you!

### CODE REVIEW

File: Source/ASVideoPlayerNode.mm [hunk 1]
```diff
@@ -95,122 +96,128 @@ @implementation ASVideoPlayerNode
...
 
-  return self;
+  ASDN::MutexLocker l(__instanceLock__);
+  
+  // Clean out pending asset
+  _pendingAsset = nil;
+  
+  // Set asset based on interface state
+  if ((ASInterfaceStateIncludesPreload(self.interfaceState))) {
+   _videoNode.asset = asset;
```
Comment (nguyenhuy) [inline Source/ASVideoPlayerNode.mm]: 1 white space missing :)

Comment (nguyenhuy) [inline Source/ASVideoPlayerNode.mm]: Also, it maybe a good idea to avoid holding the instance lock while calling the video node. Doing so might potentially cause deadlocks if videoNode (or a subclass) for some reasons walks up the node hierarchy.

File: Source/ASVideoPlayerNode.mm [hunk 2]
```diff
@@ -95,122 +96,128 @@ @implementation ASVideoPlayerNode
...
+- (NSURL *)assetURL
 {
-  if (!(self = [super init])) {
-    return nil;
+  ASDN::MutexLocker l(__instanceLock__);
+  
+  if ([_pendingAsset isKindOfClass:AVURLAsset.class]) {
+    return ((AVURLAsset *)_pendingAsset).URL;
+  } else {
+    return _videoNode.assetURL;
```
Comment (nguyenhuy) [inline Source/ASVideoPlayerNode.mm]: Same here, avoid holding instance lock while calling a subnode. Although in case of getters, the risk is very small.

File: Source/ASVideoPlayerNode.mm [hunk 3]
```diff
@@ -220,38 +227,23 @@ - (void)didLoad
...
-  }
-}
 
-- (NSArray *)createDefaultControlElementArray
-{
-  if (_delegateFlags.delegateNeededDefaultControls) {
-    return [_delegate videoPlayerNodeNeededDefaultControls:self];
+  // If we enter preload state we apply the pending asset to load to the video node so it can start and fetch the asset
+  if (_pendingAsset != nil && _videoNode.asset != _pendingAsset) {
+    _videoNode.asset = _pendingAsset;
```
Comment (nguyenhuy) [inline Source/ASVideoPlayerNode.mm]: Same here, don't hold instance lock.

File: Source/ASVideoPlayerNode.mm (hunk 1 above)
Comment (nguyenhuy) [inline Source/ASVideoPlayerNode.mm]: Lastly, please consider adding thread assertions since these setters are probably main-thread only?

**Comment by maicki** [comment]
@nguyenhuy Comments addressed. Can you take another look over it. Thanks!

File: Source/ASVideoPlayerNode.mm [hunk 4]
```diff
@@ -95,122 +96,136 @@ @implementation ASVideoPlayerNode
...
+  
+  self.asset = [AVAsset assetWithURL:assetURL];
 }
 
--(instancetype)initWithAsset:(AVAsset *)asset videoComposition:(AVVideoComposition *)videoComposition audioMix:(AVAudioMix *)audioMix loadAssetWhenNodeBecomesVisible:(BOOL)loadAssetWhenNodeBecomesVisible
+- (NSURL *)assetURL
 {
-  if (!(self = [super init])) {
-    return nil;
+  __instanceLock__.lock();
```
Comment (nguyenhuy) [inline Source/ASVideoPlayerNode.mm]: We probably don't need this?

Comment (maicki) [inline Source/ASVideoPlayerNode.mm]: Thanks for catching that ...
