### PR TITLE
[ASTextNode] Fix wrong truncation after constrained size changes

### LINKED ISSUE #1841: Truncated ASTextNode appearing in node that should not be truncated.
ASCollectionNode, with ASCellNodes

Please note there is no cell re-use. They look similar (aside from background images) for testing purposes. This reproduces with _any_ string that gets truncated at smaller cell sizes.

Layout approach is pure `layoutSpecThatFits` from root `ASCellNode` down the view hierarchy.

In overriding `visibilityDidChange` I can see that the `constrainedSize` is correct for every node, including the text nodes that have the incorrect truncation. The `bounds`, however, are incorrect for the truncated text nodes.

After the resize transition, many nodes are properly laid out. When you scroll you _eventually_ hit cells that have the `ASTextNode` truncating the `NSAttributedString` to the same place as it was previous to the resize.

This happens regardless of text formatting or otherwise, and can be reproduced with a plain `NSAttributedString`.

In summary, if a `ASTextNode` has ever been truncated, it can appear again truncated with a larger `constrainedSize`, as if it was cached and reused or something. Important to note that this seems to happen for cells that are well out of any buffer ranges.

errrr-cat

### PR DESCRIPTION
**Pull request by maicki**
Throw away the all subcomponents to create them with the new constrained size new as well as let the truncater do it's job again for the new constrained size. This is necessary as after a truncation did happen the context would use the truncated string and not the original string to truncate based on the new constrained size

This should fix #1841 and finally #1865

### CODE REVIEW

**Comment by nguyenhuy** [comment]
LGTM! It's sad that we have to throw away these components but it's necessary to avoid nasty bugs that are hard to catch otherwise.

**Comment by Adlai-Holler** [comment]
Love this, merge it at will!

File: AsyncDisplayKit/TextKit/ASTextKitRenderer.mm [hunk 1]
```diff
@@ -123,14 +123,14 @@ - (void)setConstrainedSize:(CGSize)constrainedSize
   if (!CGSizeEqualToSize(constrainedSize, _constrainedSize)) {
     _sizeIsCalculated = NO;
```
Comment (appleguy) [inline AsyncDisplayKit/TextKit/ASTextKitRenderer.mm]: We should also reset _calculatedSize here, to CGSizeZero I guess.
