### PR TITLE
Prevent Adding View-Backed Nodes to Layer-Backed Hierarchies

### LINKED ISSUE #3038: Rotating ASDKgram Causes Crash
You have to first scroll down a few photos, and then rotate.

Reported by @ay8s on Slack.

### PR DESCRIPTION
**Pull request by Adlai-Holler**
Resolves #3038

Doing this will prevent required callbacks like `didMoveToWindow` from getting sent to our view.

### CODE REVIEW

File: AsyncDisplayKitTests/ASDisplayNodeTests.mm [hunk 1]
```diff
@@ -1098,33 +1098,34 @@ - (void)testSubnodes
...
+- (void)checkReplaceSubnodeLoaded:(BOOL)loaded layerBacked:(BOOL)isLayerBacked
 {
   DeclareNodeNamed(parent);
   DeclareNodeNamed(a);
   DeclareNodeNamed(b);
   DeclareNodeNamed(c);
+  DeclareNodeNamed(d);
 
-  for (ASDisplayNode *n in @[parent, a, b, c]) {
+  for (ASDisplayNode *n in @[parent, a, b, c, d]) {
```
Comment (Adlai-Holler) [inline AsyncDisplayKitTests/ASDisplayNodeTests.mm]: These tests forgot to set `layerBacked` on the new subnode `d` so they failed our new assertion. The method name is also super confusing so I updated it.

File: AsyncDisplayKit/ASDisplayNode.mm [hunk 2]
```diff
@@ -2551,6 +2551,11 @@ - (void)_insertSubnode:(ASDisplayNode *)subnode atSubnodeIndex:(NSInteger)subnod
     return;
   }
   
+  if (self.layerBacked && !subnode.layerBacked) {
+    ASDisplayNodeFailAssert(@"Cannot add a view-backed node as a subnode of a layer-backed node. Supernode: %@, subnode: %@", self, subnode);
```
Comment (garrettmoon) [inline AsyncDisplayKit/ASDisplayNode.mm]: I swear this type of check existed before?

Comment (Adlai-Holler) [inline AsyncDisplayKit/ASDisplayNode.mm]: I think so too, but the test that failed post-change is super old so maybe not… ¯\_(ツ)_/¯

Comment (appleguy) [inline AsyncDisplayKit/ASDisplayNode.mm]: yeah, this is really weird.  The check did exist before, but I'm not sure how long ago.  We should be pretty worried it vanished lol.
