### PR TITLE
[ASTextNode] Ensure that isTruncated computes the correct value when sizing fast-path is used.

### LINKED ISSUE #2504: -[ASTextNode isTruncated] must check truncation manually if sizing fast-path is engaged (or value may be incorrectly NO)
If a text node is rendered using the new fast-path, the `isTruncated` flag will return `NO` even when the text is truncated.

To fix this, we could add an `isTruncated` method onto the renderer. If the renderer is slow-path, then the value that we return today (`firstVisibleRange.length < _attributedText.length`) is returned. For the fast-path case, we can run another sizing pass, with unbounded height, and see if the returned height is greater than the height it returned when bounded. We cache this value in the renderer for future accesses.

### PR DESCRIPTION
**Pull request by connor**
This is an attempt to fix #2504.

@Adlai-Holler what do you think?

@garrettmoon I tried setting the context to be `self.stringDrawingContext` but that didn't work – it only worked as expected when the context is `nil`.

### CODE REVIEW

File: AsyncDisplayKit/TextKit/ASTextKitRenderer.mm [hunk 1]
```diff
@@ -299,6 +299,16 @@ - (NSUInteger)lineCount
   return lineCount;
 }
 
+- (BOOL)isTruncated
+{
+  if (self.canUseFastPath) {
+    CGRect boundedRect = [_attributes.attributedString boundingRectWithSize:CGSizeMake(_constrainedSize.width, CGFLOAT_MAX) options:NSStringDrawingUsesLineFragmentOrigin | NSStringDrawingTruncatesLastVisibleLine context:nil];
```
Comment (appleguy) [inline AsyncDisplayKit/TextKit/ASTextKitRenderer.mm]: Could you break this method call across a couple lines because of the long arguments?  Aligning on : should look nice :)

File: AsyncDisplayKit/TextKit/ASTextKitRenderer.mm [hunk 2]
```diff
@@ -299,6 +299,16 @@ - (NSUInteger)lineCount
...
+    return boundedRect.size.height > _constrainedSize.height;
```
Comment (appleguy) [inline AsyncDisplayKit/TextKit/ASTextKitRenderer.mm]: It looks like this check is safe even if attributedString is nil - a CGRectZero will be returned and this should always pass as "nope, not truncated" even if constrainedSize.height is zero.

File: AsyncDisplayKit/TextKit/ASTextKitRenderer.mm [hunk 3]
```diff
@@ -299,6 +299,16 @@ - (NSUInteger)lineCount
...
+  } else {
+    return self.firstVisibleRange.length < _attributes.attributedString.length;
+  t }
```
Comment (appleguy) [inline AsyncDisplayKit/TextKit/ASTextKitRenderer.mm]: It looks like there's a spare character here that needs to be deleted

**Comment by appleguy** [comment]
@connor looks great!  I think we can merge this.  Needs one more commit of formatting cleanup (a spare character tripped up the build, and a stylistic thing)

**Comment by connor** [comment]
Thanks @appleguy! Comments addressed.

**Comment by Adlai-Holler** [comment]
Alright thanks @connor let's take this to the hoop!
