### PR TITLE
Ensure that newly inserted section supplementary nodes are added to backing store

### LINKED ISSUE #893: [Supplementary Nodes] ASCollectionView crashed due to nil supplementary node?
I'm not sure why this is occurring, but when layoutSubviews is called on my ASCollectionViewController, it calls 
```objc 
- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath
```
and the node that is provided from 
```objc
ASCellNode *node = [_dataController supplementaryNodeOfKind:kind atIndexPath:indexPath];
```
is nil. Therefore it is not stored in `_completedNodes`.

I've been scrutinizing this section of code in `ASCollectionDataController.mm`:

```objc
- (void)willInsertSections:(NSIndexSet *)sections
{
  [_pendingNodes enumerateKeysAndObjectsUsingBlock:^(NSString *kind, NSMutableArray *nodes, BOOL *stop) {
    NSMutableArray *sectionArray = [NSMutableArray arrayWithCapacity:sections.count];
    for (NSUInteger i = 0; i < sections.count; i++) {
      [sectionArray addObject:[NSMutableArray array]];
    }
    
    [self insertSections:sectionArray ofKind:kind atIndexSet:sections completion:nil];
    [self batchLayoutNodes:nodes ofKind:kind atIndexPaths:_pendingIndexPaths[kind] completion:nil];
    _pendingNodes[kind] = nil;
    _pendingIndexPaths[kind] = nil;
  }];
}
```

This is supposed to insert the pendingSections into the completed sections, however I may be missing something but the nodes never actually get added so I wonder if the completedNodes for the supplementary views ever get populated? It doesn't seem to be a problem with the rowNodes, only kind UICollectionElementKindSectionHeader at this point.

If this code works fine, then perhaps there is a race condition where layoutSubviews is being called when the completedNodes are being populated? This event seems to occur when I scroll to the bottom of my collection view, when the first UICollectionElementKindSectionHeader view is about to be displayed. It leads me to believe the supplementary view is not being correctly cached or I have a broken implementation.

### PR DESCRIPTION
**Pull request by levi**
Fixes #893

### CODE REVIEW

**Comment by appleguy** [comment]
Fantastic, thanks for the ultra fast turnaround @levi!  Getting this into 1.9.3 because of your Sunday night work.  Community dedication right there :)

File: AsyncDisplayKit/Details/ASCollectionDataController.mm [hunk 1]
```diff
@@ -28,22 +28,30 @@ @implementation ASCollectionDataController {
...
+  self = [super initWithAsyncDataFetching:asyncDataFetchingEnabled];
+  if (self != nil) {
+    _pendingNodes = [NSMutableDictionary dictionary];
+    _pendingIndexPaths = [NSMutableDictionary dictionary];
+  }
+  return self;
+}
 
-  [[self supplementaryKinds] enumerateObjectsUsingBlock:^(NSString *kind, NSUInteger idx, BOOL *stop) {
+- (void)prepareForReloadData
```
Comment (appleguy) [inline AsyncDisplayKit/Details/ASCollectionDataController.mm]: Doesn't this potentially get called multiple times, and need to recreate the _pendingNodes and _pendingIndexPaths dictionaries?

File: AsyncDisplayKit/Details/ASCollectionDataController.mm [hunk 2]
```diff
@@ -28,22 +28,30 @@ @implementation ASCollectionDataController {
...
+{
+  NSArray *kinds = [self supplementaryKinds];
+  for (NSString *kind in kinds) {
```
Comment (appleguy) [inline AsyncDisplayKit/Details/ASCollectionDataController.mm]: Thanks for using fast enumeration!  No need for block overhead.  In this case I think it would be OK (although not much better) to call [self supplementaryKinds] in the for (), as it will only be called once.

File: AsyncDisplayKit/Details/ASCollectionDataController.mm [hunk 3]
```diff
@@ -97,25 +106,29 @@ - (void)willInsertSections:(NSIndexSet *)sections
...
     [self deleteSectionsOfKind:kind atIndexSet:sections completion:nil];
-  }];
+  }
 }
 
 - (void)prepareForReloadSections:(NSIndexSet *)sections
 {
-  [[self supplementaryKinds] enumerateObjectsUsingBlock:^(NSString *kind, NSUInteger idx, BOOL *stop) {
+  NSArray *kinds = [self supplementaryKinds];
+  for (NSString *kind in kinds) {
```
Comment (appleguy) [inline AsyncDisplayKit/Details/ASCollectionDataController.mm]: Now that I see you did the whole file - which is badass!! - it probably would be better to save the lines and do the self call inline with the for ().

File: AsyncDisplayKit/Details/ASCollectionDataController.mm (hunk 1 above)
Comment (levi) [inline AsyncDisplayKit/Details/ASCollectionDataController.mm]: The pending dictionaries exist to keep the pending state between the `prepare` and `will` methods. I've set them up to be created at initialization such that they'll remain throughout the lifetime of the collection data controller. Their contents are cleared out at the end of the `will` methods.

File: AsyncDisplayKit/Details/ASCollectionDataController.mm (hunk 3 above)
Comment (levi) [inline AsyncDisplayKit/Details/ASCollectionDataController.mm]: Yup good idea.
