### PR TITLE
Fix cell selection state issues

### LINKED ISSUE #3037: Breaking ASTableView regression in 2.0.2 - Cell selection state
Sometime between `2.0.1` and `2.0.2`, an issue related to (I think) cell reuse was introduced. 

Previously, cells correctly maintained their selection state after being reused, but as of `2.0.2`, the selection state of reused cells is "leaking" into new unrelated cells. This breaks some pretty important functionality, since selection state is no longer tracked and represented on screen accurately.

The best way to describe this is with the GIFs below:

### Correct Selection (2.0.1)

cell-edit-state-correct

### Broken Selection (2.0.2)

cell-edit-state-wrong
cell-selection-state-wrong

I wasn't able to pinpoint which commit caused this, but hopefully someone more aware of the recent changes can shed some light.

### PR DESCRIPTION
**Pull request by rewandy**
Resolves #3037

This is a do-over of c85aa11, with the following differences:
- Fixed `_ASTableViewCell` properties **always** being mutated to match corresponding `ASCellNode` passthrough properties, even when the hosted `ASCellNode` is currently `nil`. Now only inheriting passthrough properties when there’s an actual instance of `ASCellNode` to read them from.
- Corrected spelling of `ASCellNode`’s `separatorInset` property.
- Reverted `_ASCollectionViewCell` inheriting the hosted cell node’s `backgroundColor` & `clipsToBounds` properties. This seems to be surprising and unwanted behavior to some, as seen in #3053 and #3044.
- Moved passthrough of `UITableViewCell`’s `selectedBackgroundView` into `_ASTableViewCell`’s `-setNode:` method for consistency.

### CODE REVIEW

File: Source/ASCellNode.h [hunk 1]
```diff
@@ -182,10 +182,10 @@ typedef NS_ENUM(NSUInteger, ASCellNodeVisibilityEvent) {
  */
 @property (nonatomic) UITableViewCellAccessoryType accessoryType;
 
-/* @abstract The seperator inset of the cell seperator line
+/* @abstract The separatorInset inset of the cell separatorInset line
```
Comment (Adlai-Holler) [inline Source/ASCellNode.h]: Just `separator`

File: Source/ASTableView.mm [hunk 2]
```diff
@@ -864,7 +872,6 @@ - (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(N
     [_rangeController configureContentView:cell.contentView forCellNode:node];
 
     cell.node = node;
-    cell.selectedBackgroundView = node.selectedBackgroundView;
```
Comment (Adlai-Holler) [inline Source/ASTableView.mm]: Nice, how'd that get there 😅

File: Source/ASCellNode.h (hunk 1 above)
Comment (rewandy) [inline Source/ASCellNode.h]: Oops, too much copy-paste here. Good catch!

**Comment by rewandy** [comment]
Thanks for the review @Adlai-Holler! Much appreciated.

That one comment should now be addressed.
